plugins {
    id 'multiloader-common'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
    if (project.plugins.hasPlugin('net.neoforged.moddev')) {
        options.compilerArgs << "-AoutRefMapFile=${project.mod_id}.refmap.json"
    }
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(':common').sourceSets.main.output
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    if (it.name == 'sourcesJar') {
        from project(':common').sourceSets.main.allSource
    } else {
        from project(':common').sourceSets.main.output
    }
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    // from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    // from(configurations.commonResources)
}
