plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}


configurations.all {
    resolutionStrategy {
        force 'org.ow2.asm:asm:9.7'
        force 'org.ow2.asm:asm-commons:9.7'
        force 'org.ow2.asm:asm-util:9.7'
        force 'org.ow2.asm:asm-tree:9.7'
        force 'org.ow2.asm:asm-analysis:9.7'
    }
}

repositories {
    maven {
        url "https://maven2.bai.lol"
        content {
            includeGroup "lol.bai"
        }
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
    maven {
        url "https://repo1.maven.org/maven2"
        name "jython"
    }
    maven {
        url = "https://maven.isxander.dev/releases"
        name = "Xander Maven"
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    implementation "lol.bai:badpackets:forge-${badpackets_version}"

    implementation("dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge") {
        exclude group: 'org.ow2.asm'
    }

    implementation("org.python:jython-slim:${jython_version}")
    additionalRuntimeClasspath "org.python:jython-slim:${project.jython_version}"

    jarJar("org.python:jython-slim:${project.jython_version}")
    jarJar("com.github.jnr:jnr-posix:3.1.15")
    jarJar("com.github.jnr:jnr-constants:0.10.3")
    jarJar("com.github.jnr:jnr-ffi:2.2.12")
    jarJar("org.antlr:antlr:3.5.2")
    jarJar("org.antlr:antlr-runtime:3.5.2")

    implementation "lol.bai:badpackets:neo-${badpackets_version}"
    jarJar "lol.bai:badpackets:neo-${badpackets_version}"


    // annotationProcessor group: 'org.spongepowered', name: 'mixin', version: '0.8.5', classifier: 'processor'
}



tasks.named('compileJava', JavaCompile) {
    // options.compilerArgs << "-AoutRefMapFile=${project.mod_id}.refmap.json"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {

            client()
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

    neoForge {
        runs {
            client {
                gameDirectory = file('runs/client')
            }
        }
    }
